### ISSUE TITLE
Incompatible license terms in Makefile*

### ISSUE THREAD

**Issue by jserv** [ARMmbed/uvisor-helloworld#16]
The file `LICENSE` implies that `uvisor-helloworld` should be licensed under Apache Software License, but bot `Makefile` and `Makefile.scripts` are marked as confidential and proprietary  software.

It is insane with other uvisor related components.

**Comment by AlessandroA** [comment]
Hello @jserv thank you very much for noticing this -- it was definitely a bug. We just fixed it.
