### ISSUE TITLE
uvisor-helloworld could not work on STM32F429I-Discovery

### ISSUE THREAD

**Issue by georgekang** [ARMmbed/uvisor-helloworld#20]
Hardware Platform: STM32F429I-Discovery
uvisor-helloWorld: 283f09131921c3299165ea9778ea7b56d186db5      

By the description of README, the green LED should blink when box was read 
and executed successfully by uVisor.

However, in my case, I found red LED blinked with error pattern 2, SANITY_CHECK_FAILED,
and uVisor was at infinite loop from address 0x0800123e to 0x0800124c.

If I used the last uVisor on github(ARMmbed/uvisor@5ae721017defe310bb4c86d54ddaed42bcdd372c), no LED blinked 
and this case was recognized as failed password comparison in README.

My questions were
1. Did this mean there was no denied access captured by uVisor? 
2. I could not find any code about password comparison.  Where are they?

**Comment by jserv** [comment]
@georgekang : It is weird. Can you attach the corresponding log while uvisor falls into infinite loop on STM32F429i-Discovery?

**Comment by georgekang** [comment]
@jserv : uvisor-helloworld would fall into infinite loop when Uvisor was fetched by yotta from https://github.com/ARMmbed/uvisor-lib.  Because it was a binary release and there was no 
output log except  LED blinking.  

Besides, I find some problems when Uvisor tried to start the app program(app_start).
  (1). Accessing SYSCFG registers would cause MPU fault even through these registers were
        declared as an acl item in box (source/main-hw.h). 
```
#define MAIN_ACL(acl_list_name)                           \
    static const UvisorBoxAclItem g_main_acl[] = {        \
        {TIM2,   sizeof(*TIM2),   UVISOR_TACLDEF_PERIPH}, \
        {TIM5,   sizeof(*TIM5),   UVISOR_TACLDEF_PERIPH}, \
        {GPIOA,  sizeof(*GPIOA),  UVISOR_TACLDEF_PERIPH}, \
        {GPIOG,  sizeof(*GPIOG),  UVISOR_TACLDEF_PERIPH}, \
        /* FIXME: secure RCC/EXTI/SYSCFG */               \
        {RCC,    sizeof(*RCC),    UVISOR_TACLDEF_PERIPH}, \
        {EXTI,   sizeof(*EXTI),   UVISOR_TACLDEF_PERIPH}, \
        {SYSCFG, sizeof(*SYSCFG), UVISOR_TACLDEF_PERIPH}, \
    }
``` 

  (2).   Before real_main was executed, HAL_Init() was called to restart HAL driver.  
          However, this function would use some registers, such like FLASH and SCB, which
          were not declared in main acl list and bus fault exception would be triggered because
          these registers were used in unprivileged mode.  
   
  (3).  minar::Scheduler::start () used HAL_PWR_EnterSLEEPMode() to make core in sleeping.
         However, core would fall into exception mode with bus fault like (2) because registers in SCB
         were accessed in HAL_PWR_EnterSLEEPMode().

**Comment by meriac** [comment]
We're experiencing a related problem - I expect it will fix the previous one. When accessing the flash access control register at 0x40023c00, an exception is generated - but the MMFAR register is inconsistent and points to the previous fault.

**Comment by georgekang** [comment]
According to B.3.5.1, Relation of the MPU to the system memory map, in ARMv7-M Architecture Reference Manual, the MPU is restricted in how it can change the default memory map attributes associated with System space, that is, for addresses 0xE0000000 and higher. 

MPU could not change the permissions of System space registers like SCB, NVIC, and SysTick and we should avoid using these registers in unprivileged mode.   Currently, these registers are used in `mbed_hal_init() --> HAL_Init()` and `minar::Scheduler::start () --> HAL_PWR_EnterSLEEPMode()` and cause bus fault exception.

**Comment by meriac** [comment]
We are currently developing the feature "register level security" that takes care of that - without adding custom APIs for each of these user-cases:

https://github.com/ARMmbed/uvisor/issues/38

That feature will also enable bit level access restrictions to registers.

**Comment by georgekang** [comment]
Thank @meriac to reply my problems.  

In conclusion, some registers are critical and can not be used in unprivileged mode directly.  The new feature "register level security" will be developed in Uvisor to provide restricted access for these registers to user box which is executed in unprivileged mode. 

I look forward for further developing of this new feature.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-838

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1022

**Comment by AlessandroA** [comment]
Fixed by:
https://github.com/ARMmbed/mbed-hal-st-stm32cubef4/pull/8
https://github.com/ARMmbed/cmsis-core-stm32f4/pull/16
https://github.com/ARMmbed/cmsis-core-stm32f429xi/pull/10
https://github.com/ARMmbed/uvisor/pull/83
https://github.com/ARMmbed/uvisor/pull/81
