### ISSUE TITLE
The blue LED does not blink on K64F in debug mode

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor-helloworld#24]
When uVisor debug messages are enabled, they are so many that they prevent minar from meeting deadlines for scheduled events (blinking the blue LED). This has been observed on K64F but could affect STM32F4 as well.

Since debug messages come from high-priority interrupts (system exceptions, mainly), they always overwrite the event handler priority.

We could use yotta config symbols to conditionally define events timeouts depending on the uVisor mode (release vs debug)

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-837

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1021

**Comment by meriac** [comment]
fixed https://github.com/ARMmbed/uvisor/commit/5dba89284b6e343988bdbd41600a0fa23bc500ad
