### ISSUE TITLE
Secret Leaks out while using armcc compiler with frdm-k64f

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/uvisor-helloworld#34]
Setup: Linux, Frdm-k64f board
Compiler: GCC and ARMCC

- with GCC, PERMISSIONDENIED event happens and the board indicates that with Red blinking LED
- However with ARMCC, Blue LED blinks with a period just like the period of red LED. And when the   SW2 button is pressed, it starts to blink rapidly, indicating that the secret has leaked.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1104

**Comment by meriac** [comment]
@hasnainvirk uVisor is currently not supported un ARMCC and not part of the upcoming TecCon release - you might have used the "unsupported" mode of uvisor where all security functions are replaced by the original insecure NVIC counterparts.
