### ISSUE TITLE
uVisor example does not work on K64F

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/uvisor-helloworld#36]
The LED keeps blinking in RED color.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1134

**Comment by meriac** [comment]
Fixed by https://github.com/ARMmbed/uvisor/pull/101 (currently testing)

**Comment by meriac** [comment]
fixed https://github.com/ARMmbed/uvisor/commit/5dba89284b6e343988bdbd41600a0fa23bc500ad

**Comment by mlnx** [comment]
Verified works ok now
