### ISSUE TITLE
incorrect behavior with stm32f429i-disco-gcc target

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/uvisor-helloworld#37]
The readme says the green led should blink at 1 second intervals at the start.  However the read led is blinking and it is much slower, approximately ~16 sec intervals.  

The user button appears to do nothing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1133

**Comment by meriac** [comment]
Fixed by https://github.com/ARMmbed/uvisor/pull/101 (currently testing)
