### ISSUE TITLE
How to link a static library to the executable

### ISSUE THREAD

**Issue by JaredCJR** [ARMmbed/uvisor-helloworld#47]
Hi,
I would like to link a static library(".a" file) provided by [CrashCatcher](https://github.com/JaredCJR/CrashCatcher/tree/merge_uVisor) into the uvisor-helloworld example,but I faced some trouble about cmake.

- I tried to add `TARGET_LINK_LIBRARIES(uvisor-helloworld /path/to/the/static/library)` in `uvisor-helloworld/yotta_targets/stm32f429i-disco-gcc/CMake/toolchain.cmake` , but it said that `Could not find cmake module file`.

Why I need to link a static library is because I would like to create a debug BOX for [post-mortem debug](https://github.com/adamgreen/CrashDebug).

Linking the library into this example would be my first step.
Could someone give me some suggestions?
Thank you very much!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1886

**Comment by 0xc0170** [comment]
There's this module (simple-binary) showing the exact feature : https://github.com/ARMmbed/simple-binary/blob/master/source/link-lib.cmake
