### ISSUE TITLE
undefined behavior in secure_compare()

### ISSUE THREAD

**Issue by avri-schneider** [ARMmbed/uvisor-helloworld#49]
`len` could be `INT_MAX`.
`diff` is declared as a `signed int`.

The assignment `while` loop block may cause `diff` value to overflow, resulting in undefined behavior (possibly setting `diff` back to `0`).

Signed integer overflow is undefined behavior in C/C++. See: http://stackoverflow.com/a/16188846/331168
> If during the evaluation of an expression, the result is not mathematically defined or not in the range of representable values for its type, the behavior is undefined

Should use `|=` operator instead of `+=` operator.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1889

**Comment by meriac** [comment]
Point taken, I see your proposal is more robust in case secure_compare would be used outside the context of uvisor_helloworld where len is limited by the target security context (https://github.com/ARMmbed/uvisor-helloworld/blob/master/source/box-challenge.cpp#L66).

Nice spot, thanks!
